[workspace]

members = [
    "user",
    "admin",
    "game",
]

resolver = "2"

[workspace.dependencies]
actix-web = "4.9.0"
config = "0.15.6"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = "1.0.217"
serde_json = "1.0.137"
snafu = "0.8.5"
